# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Work\Programs\Git\MyRepos\HeraldeTableTop\program\ui\page_add_char.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageAddChar(object):
    def setupUi(self, PageAddChar):
        PageAddChar.setObjectName("PageAddChar")
        PageAddChar.resize(526, 305)
        self.gridLayout = QtWidgets.QGridLayout(PageAddChar)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_charImageChange = QtWidgets.QPushButton(PageAddChar)
        self.pushButton_charImageChange.setObjectName("pushButton_charImageChange")
        self.gridLayout.addWidget(self.pushButton_charImageChange, 1, 0, 1, 1)
        self.label_charImage = ImageDropLabel(PageAddChar)
        self.label_charImage.setAcceptDrops(True)
        self.label_charImage.setText("")
        self.label_charImage.setObjectName("label_charImage")
        self.gridLayout.addWidget(self.label_charImage, 2, 0, 1, 1)
        self.tableWidget_sounds = QtWidgets.QTableWidget(PageAddChar)
        self.tableWidget_sounds.setObjectName("tableWidget_sounds")
        self.tableWidget_sounds.setColumnCount(2)
        self.tableWidget_sounds.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_sounds.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_sounds.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.tableWidget_sounds, 1, 1, 2, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lineEdit_charName = QtWidgets.QLineEdit(PageAddChar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_charName.sizePolicy().hasHeightForWidth())
        self.lineEdit_charName.setSizePolicy(sizePolicy)
        self.lineEdit_charName.setObjectName("lineEdit_charName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_charName)
        self.label_4 = QtWidgets.QLabel(PageAddChar)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_soundAdd = QtWidgets.QPushButton(PageAddChar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_soundAdd.sizePolicy().hasHeightForWidth())
        self.pushButton_soundAdd.setSizePolicy(sizePolicy)
        self.pushButton_soundAdd.setObjectName("pushButton_soundAdd")
        self.gridLayout_2.addWidget(self.pushButton_soundAdd, 1, 0, 1, 1)
        self.pushButton_soundRemove = QtWidgets.QPushButton(PageAddChar)
        self.pushButton_soundRemove.setObjectName("pushButton_soundRemove")
        self.gridLayout_2.addWidget(self.pushButton_soundRemove, 1, 1, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtWidgets.QLabel(PageAddChar)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_3 = QtWidgets.QLineEdit(PageAddChar)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.gridLayout_2.addLayout(self.formLayout_3, 0, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_save = QtWidgets.QPushButton(PageAddChar)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.pushButton_discard = QtWidgets.QPushButton(PageAddChar)
        self.pushButton_discard.setObjectName("pushButton_discard")
        self.horizontalLayout.addWidget(self.pushButton_discard)
        self.pushButton_new = QtWidgets.QPushButton(PageAddChar)
        self.pushButton_new.setObjectName("pushButton_new")
        self.horizontalLayout.addWidget(self.pushButton_new)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 2)

        self.retranslateUi(PageAddChar)
        QtCore.QMetaObject.connectSlotsByName(PageAddChar)

    def retranslateUi(self, PageAddChar):
        _translate = QtCore.QCoreApplication.translate
        PageAddChar.setWindowTitle(_translate("PageAddChar", "Form"))
        self.pushButton_charImageChange.setText(_translate("PageAddChar", "Change Image"))
        self.tableWidget_sounds.setSortingEnabled(True)
        item = self.tableWidget_sounds.horizontalHeaderItem(0)
        item.setText(_translate("PageAddChar", "Sound Id"))
        item = self.tableWidget_sounds.horizontalHeaderItem(1)
        item.setText(_translate("PageAddChar", "File Name"))
        self.label_4.setText(_translate("PageAddChar", "Character Name"))
        self.pushButton_soundAdd.setText(_translate("PageAddChar", "Add Sound"))
        self.pushButton_soundRemove.setText(_translate("PageAddChar", "Remove Selected\n"
"Sound"))
        self.label.setText(_translate("PageAddChar", "Sound Id:"))
        self.pushButton_save.setText(_translate("PageAddChar", "Save"))
        self.pushButton_discard.setText(_translate("PageAddChar", "Discard"))
        self.pushButton_new.setText(_translate("PageAddChar", "New"))
from ..widgets.imagedroplabel import ImageDropLabel
