# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Work\Programs\Git\MyRepos\HeraldeTableTop\program\ui\page_add_background.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageAddBackground(object):
    def setupUi(self, PageAddBackground):
        PageAddBackground.setObjectName("PageAddBackground")
        PageAddBackground.resize(573, 470)
        self.gridLayout_2 = QtWidgets.QGridLayout(PageAddBackground)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_save = QtWidgets.QPushButton(PageAddBackground)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.pushButton_discard = QtWidgets.QPushButton(PageAddBackground)
        self.pushButton_discard.setObjectName("pushButton_discard")
        self.horizontalLayout.addWidget(self.pushButton_discard)
        self.pushButton_new = QtWidgets.QPushButton(PageAddBackground)
        self.pushButton_new.setObjectName("pushButton_new")
        self.horizontalLayout.addWidget(self.pushButton_new)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(PageAddBackground)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_sceneName = QtWidgets.QLineEdit(PageAddBackground)
        self.lineEdit_sceneName.setObjectName("lineEdit_sceneName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_sceneName)
        self.gridLayout_2.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(PageAddBackground)
        self.tabWidget.setObjectName("tabWidget")
        self.layer1 = QtWidgets.QWidget()
        self.layer1.setObjectName("layer1")
        self.gridLayout = QtWidgets.QGridLayout(self.layer1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_imageLayer1 = ImageDropLabel(self.layer1)
        self.label_imageLayer1.setAcceptDrops(True)
        self.label_imageLayer1.setText("")
        self.label_imageLayer1.setObjectName("label_imageLayer1")
        self.gridLayout.addWidget(self.label_imageLayer1, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.layer1)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_imageLayer1 = QtWidgets.QLineEdit(self.layer1)
        self.lineEdit_imageLayer1.setObjectName("lineEdit_imageLayer1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_imageLayer1)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.tabWidget.addTab(self.layer1, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(PageAddBackground)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PageAddBackground)

    def retranslateUi(self, PageAddBackground):
        _translate = QtCore.QCoreApplication.translate
        PageAddBackground.setWindowTitle(_translate("PageAddBackground", "Form"))
        self.pushButton_save.setText(_translate("PageAddBackground", "Save"))
        self.pushButton_discard.setText(_translate("PageAddBackground", "Discard"))
        self.pushButton_new.setText(_translate("PageAddBackground", "New"))
        self.label_3.setText(_translate("PageAddBackground", "Scene Name: "))
        self.label_2.setText(_translate("PageAddBackground", "Ambiance Music: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.layer1), _translate("PageAddBackground", "Layer 1"))
from imagedroplabel import ImageDropLabel
