const level1_spell_list = {
    // Add more spells as needed
    FIREBALL : new Spell('Fireball', 
        [classType.WIZARD], 
        statType.INT, 
        [damageType.FIRE], 
        'Conjure a glowing ball of fire.', 
        [new ManaEffect(2, new AdditionalEffect(characterActions.ATTACKING, additionalEffects.ATTACK_RADIUS_BONUS, 1, 'Increase Attack Radius by 1'))], 
        new SpellPattern(patterns.CIRCULAR, 12, 3, 1),
        '2d6'),
    ICE_SHARD : new Spell('Ice Shard', 
        [classType.WIZARD, classType.SORCERER], 
        statType.INT, 
        [damageType.COLD], 
        'A shard of ice shoots forth from your hand.', 
        [new ManaEffect(1, new AdditionalEffect(characterActions.ATTACKING, additionalEffects.ATTACK_BONUS, 2, 'Increase Attack Damage by 2'))], 
        new SpellPattern(patterns.TARGET, 60, 0, 1),
        '1d6'),
    LIGHTNING_BOLT : new Spell('Lightning Bolt', 
        [classType.WIZARD, classType.SORCERER], 
        statType.INT, 
        [damageType.LIGHTNING], 
        'A bolt of lightning shoots forth from your hand.', 
        [new ManaEffect(3, new AdditionalEffect(characterActions.ATTACKING, additionalEffects.ATTACK_BONUS, 3, 'Increase Attack Damage by 3'))], 
        new SpellPattern(patterns.TARGET, 100, 0, 1),
        '3d8'),
    };