const level1_spell_list = {
    // Add more spells as needed
    FIREBALL : new Spell('Fireball', 
        [ClassType.WIZARD], 
        StatType.INT, 
        [DamageType.FIRE], 
        'Conjure a glowing ball of fire.', 
        [new ManaEffect(2, new AdditionalEffect(ExtraEffects.ATTACK_RADIUS_BONUS, 1, 'Increase Attack Radius by 1'))], 
        new SpellPattern(Patterns.CIRCULAR, 12, 3, 1),
        '2d6'),
    ICE_SHARD : new Spell('Ice Shard', 
        [ClassType.WIZARD, ClassType.SORCERER], 
        StatType.INT, 
        [DamageType.COLD], 
        'A shard of ice shoots forth from your hand.', 
        [new ManaEffect(1, new AdditionalEffect(ExtraEffects.ATTACK_BONUS, 2, 'Increase Attack Damage by 2'))], 
        new SpellPattern(Patterns.TARGET, 60, 0, 1),
        '1d6'),
    LIGHTNING_BOLT : new Spell('Lightning Bolt', 
        [ClassType.WIZARD, ClassType.SORCERER], 
        StatType.INT, 
        [DamageType.LIGHTNING], 
        'A bolt of lightning shoots forth from your hand.', 
        [new ManaEffect(3, new AdditionalEffect(ExtraEffects.ATTACK_BONUS, 3, 'Increase Attack Damage by 3'))], 
        new SpellPattern(Patterns.TARGET, 100, 0, 1),
        '3d8'),
    };